# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-13 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCard', '0002_auto_20170911_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinfo',
            old_name='userId',
            new_name='userId_id',
        ),
    ]
