# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-13 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCard', '0003_auto_20170913_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinfo',
            old_name='userId_id',
            new_name='userId',
        ),
    ]
