# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCard', '0004_auto_20170913_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('createTime', models.DateField(auto_now=True)),
                ('updateTime', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
