# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCard', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField(max_length=150)),
                ('productName', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('status', models.IntegerField(default=0)),
                ('inventory', models.IntegerField()),
                ('createTime', models.DateField(auto_now=True)),
                ('updateTime', models.DateField(auto_now_add=True)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditCard.category')),
            ],
        ),
    ]
