# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCard', '0007_auto_20170920_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=18)),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductPrice', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=18)),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductPrice', models.PositiveIntegerField()),
                ('ProductNumber', models.PositiveIntegerField(default=100)),
                ('ProductOffer', models.CharField(max_length=30)),
            ],
        ),
    ]
