# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditCard', '0008_mycars_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(),
        ),
    ]
